services:
  back:
    build: deploy/.
    ports: 
      - "5000:5000"
    networks:
      - default

  front:
    build: frontend/.
    ports: 
      - "80:80"
    depends_on:
      - back
    networks:
      - default

networks:
  default:
    name: existing-network